version: '3.9'
services:
  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - 5433:5432
    networks:
      - postgres
  cadastrol_server:
    container_name: cadastrol_server
    build: 
      context: .
      dockerfile: Dockerfile.srv
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres
networks:
  postgres:
    name: postgres
