version: '3.9'
services:
  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: Dockerfile.pg
    expose:
      - 5432
    networks:
      - postgres
  btalert_server_dev:
    container_name: btalert_server_dev
    build: 
      context: .
      dockerfile: Dockerfile.srv.dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres
    volumes:
      - .:/usr/src/app
networks:
  postgres:
    name: postgres