version: '3.7'
services:

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: postgres/dockerfile.postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - "./postgres/postgresql.conf:/usr/local/etc/postgres/postgresql.conf"
    command: "postgres -c config_file=/usr/local/etc/postgres/postgresql.conf"
    networks:
      - backend_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M

  cadastrol-server:
    container_name: cadastrol-server
    build:
      context: .
      dockerfile: src/dockerfile.java-maven
    restart: unless-stopped
    ports:
      - 8090:8090
    depends_on:
      - postgres
    networks:
      - backend_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/dockerfile.nginx
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - cadastrol-server
    networks:
      - backend_network

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - backend_network

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend_network

  pg-exporter:
    container_name: pg-exporter
    restart: unless-stopped
    build:
      context: .
      dockerfile: postgres/dockerfile.pg-exporter
    ports:
      - 9630:9630
    depends_on:
      - postgres
    networks:
      - backend_network

  prometheus:
    container_name: prometheus
    build:
      context: .
      dockerfile: prometheus/dockerfile.prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9090:9090
    depends_on:
      - nginx
      - node-exporter
      - cadvisor
      - pg-exporter
    networks:
      - backend_network

  grafana:
    container_name: grafana
    build:
      context: .
      dockerfile: grafana/dockerfile.grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - backend_network

  alertmanager:
    container_name: alertmanager
    build:
      context: .
      dockerfile: prometheus/alertmanager/dockerfile.alertmanager
    command: --config.file=/home/alertmanager.yml
    restart: unless-stopped
    ports:
      - 9093:9093
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network
