version: '3.9'
services:
  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - 5433:5432
    networks:
      - postgres
  cadastrol_server:
    container_name: cadastrol_server
    build: 
      context: .
      dockerfile: Dockerfile.srv
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
    - "8000:8000"
  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - nginx
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
    links:
    - prometheus
networks:
  postgres:
    name: postgres