global:
  scrape_interval: 15s 
  evaluation_interval: 15s 
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx-vts'
    metrics_path: 'api/v1/metrics'
    static_configs:
      - targets: ['nginx:8000']
