apiVersion: 1

deleteDatasources:
   - name: PROMETHEUS
     orgId: 1

datasources:
 - name: Prometheus 
   type: prometheus
   access: direct
   orgId: 1
   url: http://localhost:9090
   isDefault: true
   jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
   # <string> json object of data that will be encrypted.
   secureJsonData:
   version: 1
   editable: false

